#!/bin/sh
DISTRO="linux-x64"

# Uncomment this to install necessary C libraries
# May need to change to your distro's package manager
# sudo apt install -y build-essential

# Uncomment this if you face any BSON/MongoDB related errors
# May need to change to your distro's package manager
# sudo apt install -y libbson-dev libmongoc-dev

# If you need to install mprocs, you can use this
# npm i -g mprocs

if [ ! -d "./.lua" ]; then
    echo "Installing localua"
    curl https://loadk.com/localua.sh | bash -s .lua
fi

if [ ! -f "./tailwindcss" ]; then
    echo "Installing tailwindcss cli"
    curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-$version
    chmod +x tailwindcss-$version
    mv tailwindcss-$version tailwindcss
fi

echo "Installing rocks from rockspec"
.lua/bin/luarocks install --only-deps --tree=.lua --local ./lua-htmx-dev-1.rockspec
