#!/bin/sh
version="linux-x64"

# Uncomment this if you face the `"missing lua.h"` error
# May need to change to your distro's package manager
# echo "Installing apt deps"
# sudo apt install -y liblua5.4-dev

# Uncomment this if you face any BSON/MongoDB related errors
# May need to change to your distro's package manager
# sudo apt install -y libbson-dev libmongoc-dev

# Uncomment this to install `inotify-tools`
# May need to change to your distro's package manager
# sudo apt install -y inotify-tools

# If you need to install mprocs, you can use this
# npm i -g mprocs

# Install luarocks globally
# if ! command -v -- "luarocks" > /dev/null 2>&1; then
#   cwd=$(pwd)
#   echo "Installing luarocks"
#   cd /tmp
#   wget https://luarocks.org/releases/luarocks-3.9.2.tar.gz
#   tar zxpf luarocks-3.9.2.tar.gz
#   cd luarocks-3.9.2
#   ./configure && make && sudo make install
#   cd ..
#   rm -rf luarocks-3.9.2.tar.gz luarocks-3.9.2
#   cd $cwd
# fi

if [ ! -f "./tailwindcss" ]; then
  echo "Installing tailwindcss cli"
  curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-$version
  chmod +x tailwindcss-$version
  mv tailwindcss-$version tailwindcss
fi

echo "Installing rocks from rockspec"
./luarocks install --only-deps ./lua-htmx-dev-1.rockspec
